### PR TITLE
Range Sliders Implementation

### PR DESCRIPTION
**Pull request by wgw0**
## Range Sliders Output Fix

Previously the range sliders were usable but their output was not actually being used to calculate the grades because I hadn't altered the input types for those existing functions.
I have now done so and the page calculates the grades based on the range inputs.

This involved:
1. Changing the input async loader in the init func to update on range-input type inputs.
2. Repointing the const variables in the "gatherMarksFromPage" func to take input from range-input types.

This branch should be working properly. If it doesn't work for some reason on your end please mention it.

_(I also added another error log into a cache func in the service worker. Altered default grade to 40 for ease of dev. Also added image to cacheable)_

### CODE REVIEW

**Review by NikBit101 — DISMISSED** [review]

**Review by NikBit101 — CHANGES_REQUESTED** [review]
Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.

Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.

**Comment by wgw0** [comment]
Okay, I’ll work on handling for that.

**Comment by wgw0** [comment]
> Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.
> 
> Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.

I'm not sure how to do this? I've tried a few things that haven't made much difference. Do you have any ideas?

**Comment by m0urao** [comment]
I can do this already, can you @wgw0 ?

> Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.
> 
> Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.

**Review by m0urao — APPROVED** [review]

**Comment by wgw0** [comment]
> I can do this already, can you @wgw0 ?
> 
> > Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.
> > Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.

You can implement a feature so that they are blocked from inputting text? I thought that having type set as number would be enough and I tried some other methods with regex and stuff but it wouldn't make any difference.
If you have a method please go ahead and implement it.

**Comment by m0urao** [comment]
> > I can do this already, can you @wgw0 ?
> > > Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.
> > > Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.
> 
> You can implement a feature so that they are blocked from inputting text? I thought that having type set as number would be enough and I tried some other methods with regex and stuff but it wouldn't make any difference. If you have a method please go ahead and implement it.

So the thing is:
When I move the slider to get a number, if I try to put a letter in there, it doesn't work so this wouldn't be a problem, however on @NikBit101 's side, if he does the same thing, he can actually put letters in that field. Can you do that as well or is just a @NikBit101 's problem?

**Comment by wgw0** [comment]
> > > I can do this already, can you @wgw0 ?
> > > > Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.
> > > > Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.
> > 
> > 
> > You can implement a feature so that they are blocked from inputting text? I thought that having type set as number would be enough and I tried some other methods with regex and stuff but it wouldn't make any difference. If you have a method please go ahead and implement it.
> 
> So the thing is: When I move the slider to get a number, if I try to put a letter in there, it doesn't work so this wouldn't be a problem, however on @NikBit101 's side, if he does the same thing, he can actually put letters in that field. Can you do that as well or is just a @NikBit101 's problem?

I cannot put any letters in there, it just ignores them and doesn't take the text inputs. Only the numerical inputs. So that's why I'm a bit confused about how to fix it.

**Comment by m0urao** [comment]
> > > > I can do this already, can you @wgw0 ?
> > > > > Looks good, the only improvement I recommend is NOT allow text input into numeric values for grades.
> > > > > Yes, it warns the user but it still allows to input text and causes weird issue on my end if I do text.
> > > 
> > > 
> > > You can implement a feature so that they are blocked from inputting text? I thought that having type set as number would be enough and I tried some other methods with regex and stuff but it wouldn't make any difference. If you have a method please go ahead and implement it.
> > 
> > 
> > So the thing is: When I move the slider to get a number, if I try to put a letter in there, it doesn't work so this wouldn't be a problem, however on @NikBit101 's side, if he does the same thing, he can actually put letters in that field. Can you do that as well or is just a @NikBit101 's problem?
> 
> I cannot put any letters in there, it just ignores them and doesn't take the text inputs. Only the numerical inputs. So that's why I'm a bit confused about how to fix it.

Okay then is just @NikBit101 , I think we can merge it anyways because it's not a big problem rn, we can try to fix it later.

**Comment by m0urao** [comment]
⚠️⚠️⚠️⚠️⚠️**DON'T MERGE THIS BRANCH**⚠️⚠️⚠️⚠️⚠️

**Pull request closed without merging**
